version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recura-app
    restart: always
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
      - storage_data:/var/www/src/storage/app/public
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: recura_db
      DB_USERNAME: recura_user
      DB_PASSWORD: recura_password
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: recura-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src
      - storage_data:/var/www/src/storage/app/public # web server bhi volume access karega
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: recura-db
    restart: always
    environment:
      MYSQL_DATABASE: recura_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: recura_password
      MYSQL_USER: recura_user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  storage_data: # Naya named volume uploads ke liye